/* 
    Author: Kotkar Anket Sanjay
    Roll Number: 180101037

    Commands to execute the program:

    $ javac Assignment1Q1.java
    $ java Assignment1Q1 <number_of_threads>

    for example:
    $ javac Assignment1Q1.java
    $ java Assignment1Q1 7
*/

import java.lang.String;
import java.util.concurrent.atomic.AtomicInteger;
import java.lang.Math;

public class Assignment1Q1 {

    // counting the total points generated and how many of them lie within the unit
    // circle by all threads
    // atomic so only one thread can modify the variable at a time
    private AtomicInteger total_points = new AtomicInteger(0);
    private AtomicInteger points_inside_circle = new AtomicInteger(0);

    // class extending thread class for the purpose of multithreading
    class MonteCarlo extends Thread {

        private int iterations; // points to be generated by the thread

        public MonteCarlo(int iter) {
            iterations = iter;
            start(); // starting the thread running
        }

        public void run() {
            for (int i = 0; i < iterations; i++) {
                double x = 2 * Math.random() - 1;
                double y = 2 * Math.random() - 1;
                if (x * x + y * y <= 1) {
                    points_inside_circle.addAndGet(1);
                }
                total_points.addAndGet(1);
            }
        }
    }

    public static void main(String[] args) {

        try {
            Assignment1Q1 assignment1q1 = new Assignment1Q1();

            if (Integer.parseInt(args[0]) < 4 || Integer.parseInt(args[0]) > 16) {
                throw new Exception();
            }

            System.out.println("Number of threads created " + args[0]);
            assignment1q1.count(args);
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Number of threads to be generated was not provided.");
        } catch (Exception e) {
            System.out.println("Number of threads should be between 4 to 16. Error while executing the program.");
        }
    }

    public void count(String[] args) {

        int num_of_threads = Integer.parseInt(args[0]); // number of threads to be generated
        int total_iters = 1000000;
        int temp_iter = total_iters / num_of_threads;

        // threads generated - storing them in array of class extending thread class
        MonteCarlo threads[] = new MonteCarlo[num_of_threads];

        for (int i = 0; i < num_of_threads; i++) {
            if (i < total_iters % num_of_threads) {
                threads[i] = new MonteCarlo(temp_iter + 1);
            } else {
                threads[i] = new MonteCarlo(temp_iter);
            }
        }

        // checking whether any of the thread is alive
        for (int i = 0; i < num_of_threads; i++) {
            while (threads[i].isAlive())
                ;
        }

        // calculate value of PI
        calculatePI(num_of_threads);
    }

    public void calculatePI(int num_of_threads) {

        double d = 4.0 * points_inside_circle.doubleValue() / total_points.doubleValue();
        System.out.println("Total number of points generated: " + total_points);
        System.out.println("Total number of points inside unit circle: " + points_inside_circle);
        System.out.println("Calculated value of PI is " + d);
        System.out.println(
                "Difference between calculated value and value in Math library is " + String.valueOf(d - Math.PI));
    }
}
